--------------------------------------------------------
--  DDL for schema ESHOP
--------------------------------------------------------
DROP SCHEMA IF EXISTS ESHOP;
CREATE SCHEMA IF NOT EXISTS ESHOP;

--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------
DROP TABLE IF EXISTS ESHOP.CATEGORIES;
CREATE TABLE IF NOT EXISTS ESHOP.CATEGORIES
(
    ID    INT          NOT NULL AUTO_INCREMENT,
    NAME  VARCHAR(45)  NOT NULL,
    IMAGE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_CATEGORIES_CATEGORY_ID_UNIQUE (ID ASC),
    UNIQUE INDEX IDX_CATEGORIES_NAME_UNIQUE (NAME ASC)
);

--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------
DROP TABLE IF EXISTS ESHOP.USERS;
CREATE TABLE IF NOT EXISTS ESHOP.USERS
(
    ID       INT          NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(45)  NOT NULL,
    SURNAME  VARCHAR(45)  NOT NULL,
    EMAIL    VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(50)  NOT NULL,
    DATE     VARCHAR(50)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_USERS_USER_ID_UNIQUE (ID ASC),
    UNIQUE INDEX IDX_USERS_EMAIL_UNIQUE (EMAIL ASC),
    UNIQUE INDEX IDX_USERS_PASSWORD_UNIQUE (PASSWORD ASC)
);

--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------
DROP TABLE IF EXISTS ESHOP.PRODUCTS;
CREATE TABLE IF NOT EXISTS ESHOP.PRODUCTS
(
    ID          INT          NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(300) NULL,
    PRICE       INT          NOT NULL,
    CATEGORY_ID INT          NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_PRODUCTS_ID_UNIQUE (ID ASC),
    CONSTRAINT FK_PRODUCTS_CATEGORY_ID_CATEGORIES_ID
        FOREIGN KEY (CATEGORY_ID)
            REFERENCES ESHOP.CATEGORIES (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);


DROP TABLE IF EXISTS ESHOP.IMAGES;
CREATE TABLE IF NOT EXISTS ESHOP.IMAGES
(
    ID             INT          NOT NULL AUTO_INCREMENT,
    IMAGE          VARCHAR(100) NOT NULL,
    CATEGORY_ID    INT,
    SUBCATEGORY_ID INT,
    PRODUCT_ID     INT,
    PRIMARY_FLAG   boolean,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_IMAGES_ID_UNIQUE (ID ASC),
    CONSTRAINT FK_IMAGES_CATEGORY_ID_CATEGORIES_ID
        FOREIGN KEY (CATEGORY_ID)
            REFERENCES ESHOP.CATEGORIES (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT FK_IMAGES_SUBCATEGORY_ID_SUBCATEGORIES_ID
        FOREIGN KEY (SUBCATEGORY_ID)
            REFERENCES ESHOP.SUBCATEGORIES (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT FK_IMAGES_PRODUCT_ID_PRODUCTS_ID
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES ESHOP.PRODUCTS (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);


DROP TABLE IF EXISTS ESHOP.ORDERS;
CREATE TABLE IF NOT EXISTS ESHOP.ORDERS
(
    ID      INT         NOT NULL AUTO_INCREMENT,
    PRICE   INT         NOT NULL,
    DATE    VARCHAR(50) NOT NULL,
    USER_ID INT         NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_ORDERS_ORDER_ID_UNIQUE (ID ASC),
    FOREIGN KEY (USER_ID)
        REFERENCES ESHOP.USERS (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
.

DROP TABLE IF EXISTS ESHOP.CATEGORYIMAGES;
CREATE TABLE IF NOT EXISTS ESHOP.CATEGORYIMAGES
(
    ID          INT          NOT NULL AUTO_INCREMENT,
    IMAGE       VARCHAR(100) NOT NULL,
    CATEGORY_ID INT          NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_CATEGORYIMAGES_ID_UNIQUE (ID ASC),
    CONSTRAINT FK_CATEGORYIMAGES_CATEGORY_ID_CATEGORIES_ID
        FOREIGN KEY (CATEGORY_ID)
            REFERENCES ESHOP.CATEGORIES (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ESHOP.PRODUCTIMAGES;
CREATE TABLE IF NOT EXISTS ESHOP.PRODUCTIMAGES
(
    ID           INT          NOT NULL AUTO_INCREMENT,
    IMAGE        VARCHAR(100) NOT NULL,
    CATEGORY_ID  INT          NOT NULL,
    PRODUCT_ID   INT          NOT NULL,
    PRIMARY_FLAG boolean,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_PRODUCTIMAGES_ID_UNIQUE (ID ASC),
    CONSTRAINT FK_PRODUCTIMAGES_PRODUCT_ID_PRODUCTS_ID
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES ESHOP.PRODUCTS (ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ESHOP.SUBCATEGORIES;
CREATE TABLE IF NOT EXISTS ESHOP.SUBCATEGORIES
(
    ID          INT          NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(45)  NOT NULL,
    DESCRIPTION VARCHAR(300) NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_SUBCATEGORIES_SUBCATEGORY_ID_UNIQUE (ID ASC),
    UNIQUE INDEX IDX_SUBCATEGORIES_NAME_UNIQUE (NAME ASC)
);